### ISSUE TITLE
QT: pressing ok on setting hotkey causes crash

### ISSUE THREAD

**Issue by BlueDrink9** [BlueDrink9/autokey#5]
```
Traceback (most recent call last):
  File "/home/user/src/autokey/lib/autokey/qtui/settingswidget.py", line 192, in on_set_hotkey_button_pressed
    modifiers = self.hotkey_settings_dialog.get_active_modifiers()
AttributeError: 'HotkeySettingsDialog' object has no attribute 'get_active_modifiers'
Fatal Python error: Aborted

Thread 0x00007fdf7b7fe640 (most recent call first):
  File "/home/user/.local/lib/python3.9/site-packages/pyinotify.py", line 1194 in check_events
  File "/home/user/src/autokey/lib/autokey/monitor.py", line 125 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fdf7bfff640 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/queue.py", line 171 in get
  File "/home/user/src/autokey/lib/autokey/iomediator/iomediator.py", line 118 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fdf88837640 (most recent call first):
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 561 in send_and_recv
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1381 in reply
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1369 in __init__
  File "/usr/lib/python3.9/site-packages/Xlib/ext/record.py", line 220 in __init__
  File "/usr/lib/python3.9/site-packages/Xlib/ext/record.py", line 239 in enable_context
  File "/home/user/src/autokey/lib/autokey/interface.py", line 1189 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fdf89078640 (most recent call first):
  File "/home/user/src/autokey/lib/autokey/interface.py", line 907 in __flush_events
  File "/home/user/src/autokey/lib/autokey/interface.py", line 886 in __flush_events_loop
  File "/usr/lib/python3.9/threading.py", line 910 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fdf89879640 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/queue.py", line 171 in get
  File "/home/user/src/autokey/lib/autokey/interface.py", line 160 in __eventLoop
  File "/usr/lib/python3.9/threading.py", line 910 in run
  File "/usr/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00007fdf97d58740 (most recent call first):
  File "/home/user/src/autokey/lib/autokey/qtapp.py", line 105 in __init__
  File "/home/user/.local/bin/autokey-qt", line 33 in <module>
zsh: abort (core dumped)  autokey-qt -c
```

**Comment by BlueDrink9** [comment]
Also applise to autokey-app
